// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: server_config.proto

#include "server_config.pb.h"
#include "server_config.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace server_config {

static const char* Server_method_names[] = {
  "/server_config.Server/SignIn",
  "/server_config.Server/Login",
};

std::unique_ptr< Server::Stub> Server::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Server::Stub> stub(new Server::Stub(channel, options));
  return stub;
}

Server::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SignIn_(Server_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Login_(Server_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Server::Stub::SignIn(::grpc::ClientContext* context, const ::server_config::SignInRequest& request, ::server_config::SignInResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::server_config::SignInRequest, ::server_config::SignInResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SignIn_, context, request, response);
}

void Server::Stub::async::SignIn(::grpc::ClientContext* context, const ::server_config::SignInRequest* request, ::server_config::SignInResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::server_config::SignInRequest, ::server_config::SignInResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SignIn_, context, request, response, std::move(f));
}

void Server::Stub::async::SignIn(::grpc::ClientContext* context, const ::server_config::SignInRequest* request, ::server_config::SignInResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SignIn_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::server_config::SignInResponse>* Server::Stub::PrepareAsyncSignInRaw(::grpc::ClientContext* context, const ::server_config::SignInRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::server_config::SignInResponse, ::server_config::SignInRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SignIn_, context, request);
}

::grpc::ClientAsyncResponseReader< ::server_config::SignInResponse>* Server::Stub::AsyncSignInRaw(::grpc::ClientContext* context, const ::server_config::SignInRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSignInRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Server::Stub::Login(::grpc::ClientContext* context, const ::server_config::LoginRequest& request, ::server_config::LoginResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::server_config::LoginRequest, ::server_config::LoginResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Login_, context, request, response);
}

void Server::Stub::async::Login(::grpc::ClientContext* context, const ::server_config::LoginRequest* request, ::server_config::LoginResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::server_config::LoginRequest, ::server_config::LoginResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void Server::Stub::async::Login(::grpc::ClientContext* context, const ::server_config::LoginRequest* request, ::server_config::LoginResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::server_config::LoginResponse>* Server::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::server_config::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::server_config::LoginResponse, ::server_config::LoginRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Login_, context, request);
}

::grpc::ClientAsyncResponseReader< ::server_config::LoginResponse>* Server::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::server_config::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoginRaw(context, request, cq);
  result->StartCall();
  return result;
}

Server::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Server_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Server::Service, ::server_config::SignInRequest, ::server_config::SignInResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Server::Service* service,
             ::grpc::ServerContext* ctx,
             const ::server_config::SignInRequest* req,
             ::server_config::SignInResponse* resp) {
               return service->SignIn(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Server_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Server::Service, ::server_config::LoginRequest, ::server_config::LoginResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Server::Service* service,
             ::grpc::ServerContext* ctx,
             const ::server_config::LoginRequest* req,
             ::server_config::LoginResponse* resp) {
               return service->Login(ctx, req, resp);
             }, this)));
}

Server::Service::~Service() {
}

::grpc::Status Server::Service::SignIn(::grpc::ServerContext* context, const ::server_config::SignInRequest* request, ::server_config::SignInResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Server::Service::Login(::grpc::ServerContext* context, const ::server_config::LoginRequest* request, ::server_config::LoginResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace server_config
#include <grpcpp/ports_undef.inc>

