// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: bet_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaceBetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Outcome       string                 `protobuf:"bytes,4,opt,name=outcome,proto3" json:"outcome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBetRequest) Reset() {
	*x = PlaceBetRequest{}
	mi := &file_bet_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBetRequest) ProtoMessage() {}

func (x *PlaceBetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bet_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBetRequest.ProtoReflect.Descriptor instead.
func (*PlaceBetRequest) Descriptor() ([]byte, []int) {
	return file_bet_service_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceBetRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PlaceBetRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PlaceBetRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PlaceBetRequest) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

type PlaceBetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	NewBalance    float64                `protobuf:"fixed64,3,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBetResponse) Reset() {
	*x = PlaceBetResponse{}
	mi := &file_bet_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBetResponse) ProtoMessage() {}

func (x *PlaceBetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bet_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBetResponse.ProtoReflect.Descriptor instead.
func (*PlaceBetResponse) Descriptor() ([]byte, []int) {
	return file_bet_service_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceBetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PlaceBetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PlaceBetResponse) GetNewBalance() float64 {
	if x != nil {
		return x.NewBalance
	}
	return 0
}

var File_bet_service_proto protoreflect.FileDescriptor

const file_bet_service_proto_rawDesc = "" +
	"\n" +
	"\x11bet_service.proto\x12\vbet_service\"w\n" +
	"\x0fPlaceBetRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x18\n" +
	"\aoutcome\x18\x04 \x01(\tR\aoutcome\"c\n" +
	"\x10PlaceBetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vnew_balance\x18\x03 \x01(\x01R\n" +
	"newBalance2Y\n" +
	"\x0eBettingService\x12G\n" +
	"\bPlaceBet\x12\x1c.bet_service.PlaceBetRequest\x1a\x1d.bet_service.PlaceBetResponseB\x13Z\x11bet_service/protob\x06proto3"

var (
	file_bet_service_proto_rawDescOnce sync.Once
	file_bet_service_proto_rawDescData []byte
)

func file_bet_service_proto_rawDescGZIP() []byte {
	file_bet_service_proto_rawDescOnce.Do(func() {
		file_bet_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bet_service_proto_rawDesc), len(file_bet_service_proto_rawDesc)))
	})
	return file_bet_service_proto_rawDescData
}

var file_bet_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bet_service_proto_goTypes = []any{
	(*PlaceBetRequest)(nil),  // 0: bet_service.PlaceBetRequest
	(*PlaceBetResponse)(nil), // 1: bet_service.PlaceBetResponse
}
var file_bet_service_proto_depIdxs = []int32{
	0, // 0: bet_service.BettingService.PlaceBet:input_type -> bet_service.PlaceBetRequest
	1, // 1: bet_service.BettingService.PlaceBet:output_type -> bet_service.PlaceBetResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bet_service_proto_init() }
func file_bet_service_proto_init() {
	if File_bet_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bet_service_proto_rawDesc), len(file_bet_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bet_service_proto_goTypes,
		DependencyIndexes: file_bet_service_proto_depIdxs,
		MessageInfos:      file_bet_service_proto_msgTypes,
	}.Build()
	File_bet_service_proto = out.File
	file_bet_service_proto_goTypes = nil
	file_bet_service_proto_depIdxs = nil
}
